### ISSUE TITLE
SSR not work

### ISSUE THREAD

**Issue by juanpablocs** [simoneb/axios-hooks#242] opened 2020-06-03 04:19 UTC
Hi, great work.
The demo is not working

https://codesandbox.io/s/axios-hooks-ssr-example-sm7ms?file=/src/client/App.js:135-186

please check the chrome source code

**Comment by simoneb** [comment] 2020-06-03 08:06
Duplicate of https://github.com/simoneb/axios-hooks/issues/30

**Closed by simoneb** 2020-06-03 08:06 UTC
