### ISSUE TITLE
Discussion axios-hooks and redux

### ISSUE THREAD

**Issue by MAJRint** [simoneb/axios-hooks#364] opened 2020-11-10 14:18 UTC
Maybe this is not the right place to ask here but I am trying to getting my react redux ssr application to work with axios-hooks.

I already have a window global variable to load the state of the store.
window.INITIAL = ${serializer(store.getState())}
How do I handle the cache in that case?

Is this possible at all?

**Comment by simoneb** [comment] 2021-02-07 11:56
SSR support does not fully work, unfortunately. There are a few open issues about this that you may subscribe to. One is https://github.com/simoneb/axios-hooks/issues/30

**Comment by simoneb** [comment] 2021-02-07 11:57
I'm closing this as duplicate of https://github.com/simoneb/axios-hooks/issues/30

**Closed by simoneb** 2021-02-07 11:57 UTC
